apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: material-dashboard-netpol
  namespace: github-copilot-ns
  labels:
    app: material-dashboard
    app.kubernetes.io/name: material-dashboard
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app: material-dashboard
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: github-copilot-ns
    ports:
    - protocol: TCP
      port: 8080
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS outbound for external APIs and CDNs
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP outbound for external APIs
  - to: []
    ports:
    - protocol: TCP
      port: 80
