apiVersion: v1
kind: Service
metadata:
  name: material-dashboard-service
  namespace: github-copilot-ns
  labels:
    app: material-dashboard
    app.kubernetes.io/name: material-dashboard
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: material-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: material-dashboard-loadbalancer
  namespace: github-copilot-ns
  labels:
    app: material-dashboard
    app.kubernetes.io/name: material-dashboard
    app.kubernetes.io/component: loadbalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /health
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: material-dashboard
